[package]
name = "rxapi"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
derive_more = "0.99.7"
env_logger = "0.11"
